local opts = { noremap = true, silent = true }
local telescope = require("telescope.builtin")
vim.keymap.set("n", "<C-p>", ":bprev<cr>", opts)
vim.keymap.set("n", "<C-n>", ":bnext<cr>", opts)
vim.keymap.set("n", "<leader>hw", ":HopWord<cr>", opts)
vim.keymap.set("n", "<leader>ha", ":HopAnywhere<cr>", opts)
vim.keymap.set("n", "<leader>ff", telescope.find_files, opts)
vim.keymap.set("n", "<leader>dd", telescope.diagnostics, opts)
vim.keymap.set("n", "<leader>t", ":Telescope<CR>", opts)
vim.keymap.set("t", "<esc>", "<C-\\><C-n>", opts)
